# takes user inputs to write the story
adjective1 = input("Please enter an adjective: ")
noun1 = input("Please enter a noun: ")
verb1 = input("Please enter a verb: ")
noun2 = input("Please enter a noun: ")
verb2 = input("Please enter a verb: ")
adjective2 = input("Please enter an adjective: ")
noun3 = input("Please enter a noun: ")
noun4 = input("Please enter a noun: ")
verb3 = input("Please enter a verb ending in ing: ")
adjective3 = input("Please enter an adjective: ")
noun5 = input("Please enter a noun: ")
noun6 = input("Please enter a noun: ")
verb4 = input("Please enter a verb ending in ed: ")
noun7 = input("Please enter a noun: ")
adjective4 = input("Please enter an adjective: ")
adjective5 = input("Please enter an adjective: ")

# prints out the story
print(f"Once upon a time in a {adjective1} land, there was a {noun1} who had a magical ability to {verb1}. ")
print(f"Every day, the {noun2} would {verb2} through the {adjective2} forest, spreading {noun3} and {noun4} wherever they went. ")
print(f"One day, while {verb3}, they stumbled upon a {adjective3} {noun5} hidden beneath a {noun6}. ")
print(f"Curiosity {verb4} within them, and they couldn't resist exploring the {noun7}. ")
print(f"Inside, they discovered a {adjective4} treasure and realized they were destined for {adjective5} adventures beyond their wildest dreams.")
